export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'

export const USER_LOAD_REQUEST='USER_LOAD_REQUEST'
export const USER_LOAD_SUCCESS='USER_LOAD_SUCCESS'
export const USER_LOAD_FAIL='USER_LOAD_FAIL'
export const USER_LOGOUT='USER_LOGOUT'


export const GET_PRODUCTS_REQUEST='GET_PRODUCTS_REQUEST'
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL='GET_PRODUCTS_FAIL'



export const ADD_ITEM_TO_CART='ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART='REMOVE_ITEM_FROM_CART'
export const CLEAR_ITEM_FROM_CART='CLEAR_ITEM_FROM_CART'

